# Exercises

### #1 - Calculate the BMI (body mass index) on the two lists below using NDArrays...

In [3]:
import numpy as np
# formula = weight / (height**2) * 730
height = [69, 70, 71, 72, 73, 74, 75]
weight = [110, 120, 130, 140, 150, 160, 170]

# Converting height and weight lists to Numpy arrays
height_np = np.array([69, 70, 71, 72, 73, 74, 75])
weight_np = np.array([110, 120, 130, 140, 150, 160, 170])

# Calculating BMI using the formula
bmi = weight_np / (height_np ** 2) * 730

bmi_rounded = np.round(bmi, 2)

print("BMI values:")
print(bmi_rounded)

BMI values:
[16.87 17.88 18.83 19.71 20.55 21.33 22.06]


### #2 - Create a function that will take in two parameters and will create a random matrix based off of those parameters. Extra: Have additional parameters taken in that allow the user to choose the shape and data type of the matrix.

In [7]:
def create_random_matrix(rows, columns, shape='rectangular', dtype=float):
    """
    Create a random matrix based on the given parameters.
    
    Parameters:
    - rows: Number of rows in the matrix
    - columns: Number of columns in the matrix
    - shape: Shape of the matrix, either 'rectangular' or 'square'
    - dtype: Data type of the matrix elements
    
    Returns:
    - Random matrix
    """
    
    if shape == 'rectangular':
        matrix = np.random.rand(rows, columns)
    elif shape == 'square':
        size = min(rows, columns)
        matrix = np.random.rand(size, size)
    else:
        raise ValueError("Invalid shape. Choose 'rectangular' or 'square'.")
    
    # Convert matrix elements to the specified data type
    matrix = matrix.astype(dtype)
    
    return matrix

# Example usage
rows_input = 3
column_input = 4
shape_input = 'rectangular'
dtype_input = float

random_matrix = create_random_matrix(rows_input, column_input, shape_input, dtype_input)
print("Random Matrix:")
print(random_matrix)

Random Matrix:
[[0.19959035 0.02508451 0.28474539 0.93252351]
 [0.48083203 0.44841182 0.73804807 0.99995733]
 [0.79429225 0.44724637 0.28482186 0.07736952]]


### #3 - Extra: Open and load the data in the two text files that have the Boston Red Sox hitting data for the past seasons. Compare the difference in the two years by putting the data into an NDArray and running a differencial operation on it. The column to look for will be SLG.

Your output should display which year (either 2017 or 2018) was a better year based on SLG

In [ ]:
# I need guidance on this. I am unable to do this.

In [ ]:
FIELDS = ['Rk', 'Pos', 'Name', 'Age', 'G', 'PA', 'AB', 'R', 'H', '2B', '3B', 'HR', 'RBI', 'SB', 'CS', 
          'BB', 'SO', 'BA', 'OBP', 'SLG', 'OPS', 'OPS+', 'TB', 'GDP', 'HBP', 'SH', 'SF', 'IBB']

DATATYPES = [('rk', 'i'), ('pos', '|S25'), ('name', '|S25'), ('age', 'i'), ('g', 'i'), ('pa', 'i'), ('ab', 'i'),
                ('r', 'i'), ('h', 'i'), ('2b', 'i'), ('3b', 'i'), ('hr', 'i'), ('rbi', 'i'), ('sb', 'i'), ('cs', 'i'),
                ('bb', 'i'), ('so', 'i'), ('ba', 'f'), ('obp', 'f'), ('slg', 'f'), ('ops', 'f'), ('opsp', 'i'),
                ('tb', 'i'), ('gdp', 'i'), ('hbp', 'i'), ('sh', 'i'), ('sf', 'i'), ('ibb', 'i')]

#Use this function to actually open the data inside of a NDArray


